# Configuración de PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.username=postgres
#quarkus.datasource.password=tu_contraseña

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# logs
quarkus.log.file.enable=true
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] %s%e%n
quarkus.log.file.rotation.rotate-on-boot=true
quarkus.log.category."org.elias".level=DEBUG